services:
  flask_app:
    container_name: checkerpassAPI
    image: passwordchecker:1.0
    build: .
    ports:
      - "5001:5001"
    networks:
      - compose_kong-net
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - FLASK_APP=main.py
    depends_on:
      flask_db:
        condition: service_healthy 
    restart: always 
    command: sh -c "sleep 5 && python main.py" 

  flask_db:
    container_name: checkerpassDB
    image: postgres:17
    ports:
      - "5432:5432"
    networks:
      - compose_kong-net
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    restart: on-failure

networks:
  compose_kong-net: 
    external: true

volumes:
  pgdata: {}
